spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        auto_quote_keyword: true
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  holiday:
    service:
      key: ${HOLIDAY_API_KEY}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

mybatis:
  mapper-locations: mybatis/mapper/*.xml

aws:
  s3:
    bucket:
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretAccessKey: ${S3_SECRET_KEY}
      region: ap-northeast-2
      name: hr-handlers